name = "tampilkansandi"
compatibility_date = "2024-09-25"
pages_build_output_dir = "out"

[env.production]
name = "tampilkansandi"
route = { pattern = "tampilkansandi.pages.dev", custom_domain = true }